"""Données du groupe (3 hôtels), reprises du site existant Les Hôtels du Sénégal."""

HOTELS = [
    {
        "id": "royal-saly",
        "name": "Royal Saly",
        "city": "Saly",
        "country": "Sénégal",
        "stars": 5,
        "description": "Resort 5 étoiles en bord de mer sur la Petite Côte. Piscine à débordement, spa, restaurants gastronomiques et accès direct à la plage. L'endroit idéal pour un séjour all inclusive de luxe.",
        "image": "/images/hotel-royal-saly.webp",
        "price": 45000,
        "rating": 4.7,
        "tags": ["All Inclusive", "Bord de mer", "Spa", "Piscine"],
    },
    {
        "id": "pelican-du-saloum",
        "name": "Le Pélican du Saloum",
        "city": "Toubacouta",
        "country": "Sénégal",
        "stars": 4,
        "description": "Niché au cœur du Delta du Saloum, patrimoine mondial de l'UNESCO. Lodge éco-luxe avec excursions en pirogue, observation d'oiseaux et cuisine locale raffinée.",
        "image": "/images/hotel-pelican-saloum.webp",
        "price": 35000,
        "rating": 4.5,
        "tags": ["Éco-lodge", "Nature", "Excursions", "Cuisine locale"],
    },
    {
        "id": "nema-kadior",
        "name": "Le Nema Kadior",
        "city": "Casamance",
        "country": "Sénégal",
        "stars": 4,
        "description": "Boutique-hôtel de charme au cœur de la Casamance, la région la plus verdoyante du Sénégal. Architecture traditionnelle, jardins tropicaux, plages sauvages et immersion culturelle diola.",
        "image": "/images/hotel-nema-kadior.webp",
        "price": 40000,
        "rating": 4.6,
        "tags": ["Charme", "Culture", "Plage sauvage", "Jardin tropical"],
    },
]

ROOMS = [
    {"id": "rs-standard", "hotel_id": "royal-saly", "name": "Chambre Double Standard",
     "surface_m2": 22, "capacity": 2, "beds": "1 lit double ou 2 lits simples", "price_fcfa": 45000,
     "description": "Chambre double confortable en bungalow au cœur du parc arboré, décoration aux tons chauds, terrasse sur le jardin tropical.",
     "image": "/images/gallery/gallery-suite.jpg",
     "amenities": ["Climatisation", "Salle de bain privée", "Terrasse ou balcon", "TV", "Coffre-fort", "Wifi"]},
    {"id": "rs-triple", "hotel_id": "royal-saly", "name": "Chambre Triple",
     "surface_m2": 26, "capacity": 3, "beds": "1 lit double + 1 lit simple", "price_fcfa": 60000,
     "description": "Chambre spacieuse pour 3 personnes en bungalow, parfaite pour les amis ou petits groupes.",
     "image": "/images/gallery/gallery-suite.jpg",
     "amenities": ["Climatisation", "Salle de bain privée", "Terrasse ou balcon", "TV", "Coffre-fort", "Wifi"]},
    {"id": "rs-familiale", "hotel_id": "royal-saly", "name": "Chambre Familiale",
     "surface_m2": 32, "capacity": 4, "beds": "1 lit double + 2 lits simples", "price_fcfa": 78000,
     "description": "Espace généreux pour 4 personnes (2 adultes + 2 enfants), idéale pour les vacances en famille à Saly.",
     "image": "/images/gallery/gallery-suite.jpg",
     "amenities": ["Climatisation", "Salle de bain privée", "Terrasse", "TV", "Coffre-fort", "Wifi"]},
    {"id": "rs-suite", "hotel_id": "royal-saly", "name": "Suite",
     "surface_m2": 55, "capacity": 4, "beds": "1 lit king-size + canapé-lit", "price_fcfa": 110000,
     "description": "Vaste suite sur 2 niveaux avec balcon, terrasse et salon séparé. Le choix premium au Royal Saly.",
     "image": "/images/gallery/gallery-suite.jpg",
     "amenities": ["Climatisation", "Salon séparé", "Balcon", "Terrasse", "Mini-bar", "Service en chambre"]},

    {"id": "ps-case", "hotel_id": "pelican-du-saloum", "name": "Case Traditionnelle",
     "surface_m2": 28, "capacity": 2, "beds": "Lit double", "price_fcfa": 35000,
     "description": "Case rénovée avec tout le confort moderne, terrasse donnant sur les bolongs.",
     "image": "/images/gallery/gallery-suite.jpg",
     "amenities": ["Ventilateur", "Moustiquaire", "Salle d'eau", "Terrasse privée", "Vue bolong"]},
    {"id": "ps-lodge", "hotel_id": "pelican-du-saloum", "name": "Lodge Mangrove",
     "surface_m2": 36, "capacity": 2, "beds": "Lit King Size", "price_fcfa": 55000,
     "description": "Lodge sur pilotis avec vue imprenable sur la mangrove. Immersion totale dans la nature.",
     "image": "/images/gallery/gallery-suite.jpg",
     "amenities": ["Climatisation", "Minibar", "Terrasse panoramique", "Douche à l'italienne", "Vue mangrove"]},
    {"id": "ps-baobab", "hotel_id": "pelican-du-saloum", "name": "Suite Baobab",
     "surface_m2": 55, "capacity": 3, "beds": "Lit King Size + Canapé-lit", "price_fcfa": 85000,
     "description": "Suite premium avec salon, vue à 360° sur le delta et accès privatif à la piscine.",
     "image": "/images/gallery/gallery-suite.jpg",
     "amenities": ["Climatisation", "Minibar premium", "Salon", "Baignoire", "Vue 360°", "Piscine privative"]},

    {"id": "nk-diola", "hotel_id": "nema-kadior", "name": "Chambre Diola",
     "surface_m2": 30, "capacity": 2, "beds": "Lit double", "price_fcfa": 40000,
     "description": "Chambre de charme inspirée de l'architecture diola, mobilier artisanal local.",
     "image": "/images/gallery/gallery-suite.jpg",
     "amenities": ["Climatisation", "Mobilier artisanal", "Salle de bain", "Terrasse", "Jardin tropical"]},
    {"id": "nk-fromager", "hotel_id": "nema-kadior", "name": "Bungalow Fromager",
     "surface_m2": 40, "capacity": 2, "beds": "Lit King Size", "price_fcfa": 62000,
     "description": "Bungalow indépendant niché sous les fromagers centenaires, terrasse et hamac.",
     "image": "/images/gallery/gallery-suite.jpg",
     "amenities": ["Climatisation", "Minibar", "Hamac", "Terrasse privée", "Douche extérieure"]},
    {"id": "nk-villa", "hotel_id": "nema-kadior", "name": "Villa Casamance",
     "surface_m2": 80, "capacity": 4, "beds": "Lit King Size + 2 lits simples", "price_fcfa": 95000,
     "description": "Villa privée avec piscine plunge, jardin clos et service personnalisé.",
     "image": "/images/gallery/gallery-suite.jpg",
     "amenities": ["Climatisation", "Minibar premium", "Piscine plunge", "Jardin privatif", "Salon extérieur"]},
]

BLOCKED_DATES = {room["id"]: [] for room in ROOMS}
